create table if not exists endpoint_hits
(
    id        bigint generated by default as identity primary key,
    app       varchar(255) not null,
    uri       varchar(512) not null,
    ip        varchar(45)  not null,
    timestamp timestamp    not null
);

create index if not exists idx_timestamp on endpoint_hits (timestamp);
create index if not exists idx_app_uri on endpoint_hits (app, uri);

