create table if not exists users
(
    id    bigint generated by default as identity primary key,
    name  varchar(250) not null,
    email varchar(254) not null,
    constraint user_email_unique unique (email)
);

create table if not exists categories
(
    id   bigint generated by default as identity primary key,
    name varchar(50) not null,
    constraint category_name_unique unique (name)
);

create table if not exists events
(
    id                 bigint generated by default as identity primary key,
    annotation         varchar(2000) not null,
    category_id        bigint        not null references categories (id) on delete restrict,
    created_on         timestamp     not null,
    description        varchar(7000) not null,
    event_date         timestamp     not null,
    initiator_id       bigint        not null references users (id) on delete cascade,
    lat                real          not null,
    lon                real          not null,
    paid               boolean       not null,
    participant_limit  integer       not null,
    published_on       timestamp,
    request_moderation boolean       not null,
    state              varchar(20)   not null,
    title              varchar(120)  not null
);

create table if not exists requests
(
    id           bigint generated by default as identity primary key,
    created      timestamp   not null,
    event_id     bigint      not null references events (id) on delete cascade,
    requester_id bigint      not null references users (id) on delete cascade,
    status       varchar(20) not null,
    constraint request_unique unique (event_id, requester_id)
);

create table if not exists compilations
(
    id     bigint generated by default as identity primary key,
    pinned boolean     not null,
    title  varchar(50) not null
);

create table if not exists compilation_events
(
    compilation_id bigint not null references compilations (id) on delete cascade,
    event_id       bigint not null references events (id) on delete cascade,
    primary key (compilation_id, event_id)
);

create table if not exists comments
(
    id         bigint generated by default as identity primary key,
    text       varchar(2000) not null,
    event_id   bigint        not null references events (id) on delete cascade,
    author_id  bigint        not null references users (id) on delete cascade,
    created_on timestamp     not null,
    updated_on timestamp
);

create index if not exists idx_events_event_date on events (event_date);
create index if not exists idx_events_state on events (state);
create index if not exists idx_events_category_id on events (category_id);
create index if not exists idx_events_initiator_id on events (initiator_id);
create index if not exists idx_requests_event_id on requests (event_id);
create index if not exists idx_requests_requester_id on requests (requester_id);
create index if not exists idx_comments_event_id on comments (event_id);
create index if not exists idx_comments_author_id on comments (author_id);
create index if not exists idx_comments_created_on on comments (created_on);

